# Basic Settings
broker.id=1
zookeeper.connect=zookeeper:2181
log.dirs=/var/lib/kafka/data

# Security/SSL Settings
listeners=PLAINTEXT://0.0.0.0:9092,SSL://0.0.0.0:9093
advertised.listeners=PLAINTEXT://kafka:9092,SSL://localhost:9093
listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL

ssl.keystore.location=/etc/kafka/secrets/kafka-broker-keystore.jks
ssl.keystore.password=password
ssl.key.password=password
ssl.truststore.location=/etc/kafka/secrets/broker-truststore.jks
ssl.truststore.password=password
ssl.client.auth=required