# Force SSL configuration
listeners=SSL://0.0.0.0:9093,PLAINTEXT://0.0.0.0:9092
advertised.listeners=SSL://localhost:9093,PLAINTEXT://kafka:9092
listener.security.protocol.map=SSL:SSL,PLAINTEXT:PLAINTEXT

# Point directly to the mounted secrets
ssl.keystore.location=/etc/kafka/secrets/kafka-broker-keystore.jks
ssl.keystore.password=password
ssl.key.password=password
ssl.truststore.location=/etc/kafka/secrets/broker-truststore.jks
ssl.truststore.password=password
ssl.client.auth=required