import os
import sys

# 1. DLL Fix for WeasyPrint
gtk_bin_path = r"C:\Program Files\GTK3-Runtime-Win64\bin" 
if os.path.exists(gtk_bin_path):
    os.add_dll_directory(gtk_bin_path)

import swisseph as swe
import time, json
from datetime import datetime, timedelta
from pynput import keyboard
from geopy.geocoders import Nominatim
from timezonefinder import TimezoneFinder
import pytz
from rich.live import Live
from rich.table import Table
from rich.console import Console
from rich.panel import Panel
from rich.align import Align
from weasyprint import HTML

# ---------------- CONFIGURATION ----------------
JSON_FILE = "pulippani_300.json"
TRANSIT_JSON = "gochar_phaladeepika.json"
swe.set_ephe_path("./ephe")
console = Console()
geolocator = Nominatim(user_agent="pulippani_engine_v4")
tf = TimezoneFinder()

# ---------------- PDF GENERATOR LOGIC ----------------
def generate_report_pdf(user_name, dob, tob, natal_moon, analysis_results, current_date):
    html_content = f"""
    <html>
    <head>
    <style>
        @page {{ size: A4; margin: 15mm; }}
        body {{ font-family: 'Helvetica', sans-serif; color: #2c3e50; line-height: 1.6; }}
        header {{ text-align: center; border-bottom: 3px solid #3498db; margin-bottom: 20px; }}
        .profile {{ background: #ecf0f1; padding: 15px; border-radius: 5px; margin-bottom: 20px; }}
        .result-card {{ border-left: 5px solid #3498db; margin: 10px 0; padding: 10px; background: #fdfdfd; border-bottom: 1px solid #eee; }}
        .intensity {{ font-weight: bold; color: #2980b9; }}
        .sloka {{ font-style: italic; color: #7f8c8d; }}
    </style>
    </head>
    <body>
        <header><h1>Gochar Phaladeepika Intelligence Report</h1></header>
        <div class="profile">
            <strong>Native:</strong> {user_name} | <strong>Birth:</strong> {dob} {tob}<br>
            <strong>Janma Rasi:</strong> {natal_moon} | <strong>Transit Date:</strong> {current_date}
        </div>
        <h3>Planetary Analysis</h3>
        {"".join([f'<div class="result-card">{res}</div>' for res in analysis_results])}
        <footer style="text-align:center; margin-top:30px; font-size:10pt; color:#95a5a6;">
            Generated by Pulippani Engine v4.5
        </footer>
    </body>
    </html>"""
    filename = f"Transit_Report_{current_date.replace(' ', '_')}.pdf"
    HTML(string=html_content).write_pdf(filename)
    return filename

# ---------------- ENGINE CLASS ----------------
class PulippaniEngine:
    def __init__(self, name, dob, tob, city):
        swe.set_sid_mode(swe.SIDM_LAHIRI)
        self.name = name
        self.dob = dob
        self.tob = tob
        self.city = city
        self.view_date = datetime.now()
        self.lat, self.lon, self.offset, self.tz = self.get_location()
        
        d, m, y = map(int, dob.split("/"))
        hh, mm, ss = map(int, tob.split(":"))
        birth_hour_utc = (hh + mm/60 + ss/3600) - self.offset
        self.njd = swe.julday(y, m, d, birth_hour_utc)
        
        self.transit_db = self.load_json(TRANSIT_JSON)
        self.natal_planets = self.calc_planets(self.njd)
        self.lagna_lon = self.calc_lagna(self.njd)
        self.natal_moon_rasi = int(self.natal_planets["Mo"]["lon"] / 30)

    def get_location(self):
        try:
            loc = geolocator.geocode(self.city, timeout=5)
            lat, lon = (loc.latitude, loc.longitude) if loc else (16.1176, 80.9314)
            tz = tf.timezone_at(lat=lat, lng=lon) or "Asia/Kolkata"
            off = pytz.timezone(tz).localize(datetime.now()).utcoffset().total_seconds()/3600
            return lat, lon, off, tz
        except: return 16.1176, 80.9314, 5.5, "Asia/Kolkata"

    def load_json(self, filename):
        if os.path.exists(filename):
            with open(filename, 'r', encoding='utf-8') as f: return json.load(f)
        return {}

    def calc_planets(self, jd):
        flags = swe.FLG_SWIEPH | swe.FLG_SPEED | swe.FLG_SIDEREAL
        p_ids = [(0,"Su"), (1,"Mo"), (2,"Me"), (3,"Ve"), (4,"Ma"), (5,"Ju"), (6,"Sa"), (11,"Ra")]
        data = {}
        for pid, name in p_ids:
            res = swe.calc_ut(jd, pid, flags)[0]
            data[name] = {"lon": res[0], "speed": res[3]}
            if name == "Ra": data["Ke"] = {"lon": (res[0]+180)%360, "speed": res[3]}
        return data

    def calc_lagna(self, jd):
        return swe.houses_ex(jd, self.lat, self.lon, b'W')[0][0]

    def get_strength(self, p_name, lon, is_transit=True):
        deg = lon % 30
        is_odd = int(lon / 30) % 2 == 0
        stages = ["Balya", "Kumara", "Yuva", "Vriddha", "Mrita"]
        idx = int(deg / 6)
        if not is_odd: stages.reverse()
        avastha = stages[idx]
        power = {"Yuva": 1.2, "Kumara": 1.0, "Balya": 0.5, "Vriddha": 0.2, "Mrita": 0.1}.get(avastha, 1.0)
        if is_transit:
            h_lagna = (int(lon/30) - int(self.lagna_lon/30) + 12) % 12 + 1
            power *= 1.5 if 7 <= h_lagna <= 12 else 0.5
        return power, avastha
        
    def check_vedha(self, p_name, h_moon, current_sky):
        vedha_map = {
            "Su": {3: 9, 6: 12, 10: 4, 11: 1},
            "Mo": {1: 5, 3: 9, 6: 12, 7: 2, 10: 4, 11: 8},
            "Ma": {3: 12, 6: 9, 11: 5},
            "Me": {2: 5, 4: 3, 6: 9, 8: 1, 10: 7, 11: 12},
            "Ju": {2: 12, 5: 4, 7: 3, 9: 10, 11: 8},
            "Ve": {1: 8, 2: 7, 3: 1, 4: 10, 5: 9, 8: 5, 9: 11, 11: 3, 12: 6},
            "Sa": {3: 12, 6: 9, 11: 5}
        }
        if p_name not in vedha_map or h_moon not in vedha_map[p_name]: return False 
        target_h = vedha_map[p_name][h_moon]
        for other_p, data in current_sky.items():
            if other_p == p_name: continue
            if (p_name == "Su" and other_p == "Sa") or (p_name == "Sa" and other_p == "Su"): continue
            if (p_name == "Mo" and other_p == "Me") or (p_name == "Me" and other_p == "Mo"): continue
            other_h = (int(data['lon']/30) - self.natal_moon_rasi + 12) % 12 + 1
            if other_h == target_h: return True
        return False

    def get_analysis(self, for_pdf=False):
        t_jd = swe.julday(self.view_date.year, self.view_date.month, self.view_date.day, 12.0)
        current_sky = self.calc_planets(t_jd)
        results = []
        for p, data in current_sky.items():
            h_moon = (int(data['lon']/30) - self.natal_moon_rasi + 12) % 12 + 1
            power, avastha = self.get_strength(p, data['lon'])
            is_blocked = self.check_vedha(p, h_moon, current_sky)
            vedha_status = " [BLOCKER]" if is_blocked else ""
            p_full = {"Su":"Sun", "Mo":"Moon", "Me":"Mercury", "Ve":"Venus", "Ma":"Mars", "Ju":"Jupiter", "Sa":"Saturn", "Ra":"Rahu", "Ke":"Ketu"}.get(p, p)
            
            # Fetch sloka text - Fixed for Rahu/Ketu
            sloka = self.transit_db.get(p_full, {}).get(str(h_moon), {}).get("Shukla", "Data pending...")
            
            if is_blocked: sloka = "NOTICE: Positive effects obstructed (Vedha)."
            if for_pdf:
                results.append(f"<strong>{p_full}</strong> (H{h_moon}): <span class='intensity'>{power:.2f} ({avastha})</span>{vedha_status}<br><span class='sloka'>{sloka}</span>")
            else:
                color = "red" if is_blocked else "green"
                results.append(f"[{color}]{p}[/]: H{h_moon} | P:{power:.2f} ({avastha}){vedha_status}")
        return results

# ---------------- INTERACTIVE INPUT ----------------
def get_user_input():
    console.print(Panel("[bold cyan]Pulippani Gochar Engine v4.5[/]\n[italic]Interactive Birth Detail Entry[/]", expand=False))
    name = console.input("[bold yellow]Enter Name:[/] ")
    while True:
        dob = console.input("[bold yellow]Enter Date of Birth (DD/MM/YYYY):[/] ")
        try:
            datetime.strptime(dob, "%d/%m/%Y")
            break
        except: console.print("[red]Format Error! Use DD/MM/YYYY (e.g. 05/04/1980)[/]")
    while True:
        tob = console.input("[bold yellow]Enter Time of Birth (HH:MM:SS):[/] ")
        try:
            datetime.strptime(tob, "%H:%M:%S")
            break
        except: console.print("[red]Format Error! Use HH:MM:SS (e.g. 14:30:00)[/]")
    city = console.input("[bold yellow]Enter Birth City:[/] ")
    return name, dob, tob, city

# Start interaction
u_name, u_dob, u_tob, u_city = get_user_input()
engine = PulippaniEngine(u_name, u_dob, u_tob, u_city)
console.clear() # CRITICAL: Clears screen to prevent overlapping

# ---------------- KEYBOARD & LIVE UI ----------------
def on_press(key):
    try:
        if key == keyboard.Key.right: engine.view_date += timedelta(days=1)
        elif key == keyboard.Key.left: engine.view_date -= timedelta(days=1)
        elif hasattr(key, 'char') and key.char == 'p':
            res = engine.get_analysis(for_pdf=True)
            fname = generate_report_pdf(engine.name, engine.dob, engine.tob, f"Rasi {engine.natal_moon_rasi+1}", res, engine.view_date.strftime('%d-%b-%Y'))
            os.system(f"start {fname}" if sys.platform == "win32" else f"open {fname}")
    except: pass

keyboard.Listener(on_press=on_press).start()

try:
    with Live(auto_refresh=True, screen=True) as live:
        while True:
            t = Table(title=f"Transit Date: {engine.view_date:%d-%b-%Y}", show_header=False, border_style="bright_blue")
            analysis = engine.get_analysis()
            t.add_row(Panel("\n".join(analysis), title=f"Gochar Analysis for {engine.name}", subtitle="Arrows: Change Date | P: PDF Report"))
            live.update(Align.center(t))
            time.sleep(0.1)
except KeyboardInterrupt: pass